package exceptionPractises;
public class ThrowsKeywordDemo {	
	public void div(int a, int b) throws ArithmeticException
	{
		if(b==0)
		{
			throw new ArithmeticException();
		}
		else 
		{
			int c = a/b;
			System.out.println(c);
			
		}
	}
	public static void main(String[] args) throws ArithmeticException {
		// TODO Auto-generated method stub
		ThrowsKeywordDemo obj =new ThrowsKeywordDemo();
		try {
		     obj.div(12, 0);
		}
		catch(Exception e) {
			e.printStackTrace();
			System.out.println("Further code Exception");
		}

		System.out.println("Execute the code");
	}

}
